# Generated by Django 5.0.14 on 2025-06-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_group_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
